### PR TITLE
[#76] Release 2.5.0

### LINKED ISSUE #76: 2.5.0

### PR DESCRIPTION
**Pull request by marco-prontera**
closes #76

### CODE REVIEW

**Comment by Codex-** [comment]
I've built out the `relativeCssInjection` functionality in an older version of this package, if you'd be interested in seeing how I've approached it / make a PR targeting this feature branch, I can bring it up to date 🚀

**Comment by marco-prontera** [comment]
> I've built out the `relativeCssInjection` functionality in an older version of this package, if you'd be interested in seeing how I've approached it / make a PR targeting this feature branch, I can bring it up to date 🚀

Of course, you can. I'm curious about it, thank you in advance!

**Comment by Codex-** [comment]
Sounds good! I made reasonable progress on it tonight, i'll visit this on Monday, can see the changes so far here: https://github.com/Codex-/vite-plugin-css-injected-by-js/tree/implement_relative_css_injection

**Comment by marco-prontera** [comment]
> Sounds good! I made reasonable progress on it tonight, i'll visit this on Monday, can see the changes so far here: https://github.com/Codex-/vite-plugin-css-injected-by-js/tree/implement_relative_css_injection

@Codex- Only one thing, Can you base your changes on this branch instead of the main branch? 🙏

**Comment by marco-prontera** [comment]
> Sounds good! I made reasonable progress on it tonight, i'll visit this on Monday, can see the changes so far here: https://github.com/Codex-/vite-plugin-css-injected-by-js/tree/implement_relative_css_injection

There are any updates? I don't want to seem heavy, but I'm only curious if you have seen something that probably makes this "feature" not applicable for every use case. Because to me seems that for Vue isn't simple as I thought

**Comment by Codex-** [comment]
This is today's mission :)

**Pull request merged**
