### PR TITLE
fix #100

### LINKED ISSUE #100: Wrong globalCssToInject
When I build multiple single files at the same time, some introduce CSS and some do not, but in reality, all CSS is saved to gloabl, resulting in each single file introducing all CSS.

https://github.com/marco-prontera/vite-plugin-css-injected-by-js/blob/main/src/utils.ts#L228

### PR DESCRIPTION
**Pull request by shiyiya**

### CODE REVIEW

**Review by marco-prontera — CHANGES_REQUESTED** [review]
Hi, thank you for the contribution. I checked but this fix cause a bug when this plugin is used with @vitejs/plugin-legacy. Can you try by configuring the "jsAssetsFilterFunction" option? You can find all options in the readme. If anything doesn't help you, I need to see the use case so a project where this thing is used and your problem occurs

**Comment by shiyiya** [comment]
```js
//a.js
import 'a.css'

```
```js
//b.js
// no css
```

vitebuild a.js
vitebuild b.js

result:
a and b injected a.css

**Comment by marco-prontera** [comment]
@shiyiya you should try relativeCSSInjection option or the other I said. Let me know if it works

**Comment by shiyiya** [comment]
relativeCSSInjection make all non-css

**Comment by marco-prontera** [comment]
@shiyiya I think until we find another solution you can use "jsAssetsFilterFunction" option to solve your problem, maybe we can check if the user configured the lib mode so we can clear the global variable. Unfortunately I don't have the pc with me these days so I can't do all the necessary tests

**Comment by shiyiya** [comment]
Is this `generateBundle` only executed once? Should we just include `globalcss` in it?

**Comment by marco-prontera** [comment]
> Is this `generateBundle` only executed once? Should we just define `globalcss` in it?

There is a good solution for that problem. Instead of using the global css code for every user of that plugin, we should add a simple check for those who configured the lib mode, if the simple mode is enabled we can use the css code directly and skip the usage of the global css code. In that way we support the legacy plugin and prevent incorrect behavior when used in the lib mode. Can you change the code to do this? If not I can do the work and create a new version for to fix this.

**Comment by marco-prontera** [comment]
Thank you for the contribution, since I don't have much time this month I will publish a version with the fix in minutes. Hope in your contribution in the future and thank you!

**Pull request closed without merging**
